name: GitHub to Discord

on:
  push:
    branches:
      - main  # Ou une autre branche
  pull_request:
    types: [opened, closed]

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Envoyer un message formaté sur Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          PAYLOAD=$(jq -n \
            --arg username "$GITHUB_ACTOR" \
            --arg avatar_url "https://github.com/$GITHUB_ACTOR.png" \
            --arg title "Mise à jour sur $GITHUB_REPOSITORY" \
            --arg description "Commit pushé par **$GITHUB_ACTOR**" \
            --argjson color 0 \
            '{ username: $username, avatar_url: $avatar_url, embeds: [{ title: $title, description: $description, color: $color }] }')

          curl -H "Content-Type: application/json" -X POST "$DISCORD_WEBHOOK" -d "$PAYLOAD"
